id: P1FBD2373
initial_creation_type: input
source_metadata:
  title: Atiśa Dīpaṃkara Series
  language: pt
  description: Atiśa Dīpaṃkara Śrījñāna (982–1054), known as Jowo Jé Palden Atisha
    (jo bo rje dpal ldan a ti sha) in Tibetan, was a great Indian master and scholar.
    He spent the last ten years of his life in Tibet, teaching and translating texts,
    and was instrumental in reinvigorating Buddhism there after a period of persecution
    and decline.
  volume:
    c99061d569064e3ba3abfbe9fffd08d3:
      title: Heart Treasure for the Warriors Who Long for Liberation
      parent: Advice
    9e0960d6a1984ef6810c8b9889eb59aa:
      title: The Lamp for the Path to Enlightenment
      parent: Advice
    6eb1ac2342884e57b2eeaf2d208029c1:
      title: 'Bestower of Supreme Blessings: Guru Yoga of the Great Incomparable Lord
        Atiśa'
      parent: Guru Yoga
    0bdc2dacc29b40f9bfaf1d1454399cc2:
      title: The Bodhisattva’s Garland of Jewels
      parent: Mind Training
    12f68078d7c449a79a840aaff650ad58:
      title: An Extremely Concise Praise of the Twenty-One Tārās
      parent: Praise
    fd8fe90f5e0c4ac0a5569a6e9f9daa64:
      title: Light Offering Prayer
      parent: Prayers
    592374c6ec594e67af1f57fd4a66a539:
      title: Prayer for the Future of the Dharma
      parent: Prayers
    df3dd943675a47958dcce291242778a4:
      title: Prayer to Ārya Tārā
      parent: Prayers
    a958fd241e8d4584ae79650268807308:
      title: Short Prayer to Atiśa
      parent: Prayers
created_at: '2022-03-01T02:10:55.974215'
last_modified_at: '2022-03-01T02:10:55.974218'
